y2064_peine_jawoll = "Jawoll"
y2064_peine_jawoll_inside = "You are inside the market. You can buy stuff for quite cheap prices."
y2064_peine_jawoll_outside = "You found your discount supermarket directly in front of your home... lol that took too long!"
