import unittest

from gdo.base.Util import Random
from gdo.shadowdogs.actions.Action import Action
from gdo.shadowdogs.city.y2064.Peine.locations.waffenkief.Hate import Hate
from gdo.shadowdogs.test.ShadowdogsTestCase import ShadowdogsTestCase
from gdotest.TestUtil import cli_plug, all_private_messages, cli_gizmore


class ShadowdogsPeine2064Test(ShadowdogsTestCase):

    async def test_00_quest_home(self):
        gizmore = await self.fresh_gizmore(False)
        out = cli_plug(gizmore, '$sdtalk mom hello')
        self.assertIn('upset', out, 'sdtalk mom hello does not work.')
        out = cli_plug(gizmore, '$sdtalk mom work')
        self.assertIn('home', out, 'sdtalk mom hello does not work.')
        out = cli_plug(gizmore, '$sdtalk mom home')
        self.assertIn('find', out, 'sdtalk mom hello does not work.')
        out = cli_plug(gizmore, '$sdtalk mom home')
        self.assertIn('army', out, 'sdtalk mom hello does not work.')
        out = cli_plug(gizmore, '$sdqus')
        self.assertIn('Etablisment', out, 'sdtalk mom hello does not work.')
        out = cli_plug(gizmore, '$sdgml giz inside Marketpl')
        self.assertIn('Marketplace', out, 'gml mom hello does not work.')
        out = cli_plug(gizmore, '$sdtalk moell hello')
        out = cli_plug(gizmore, '$sdtalk moell home')
        out = cli_plug(gizmore, '$sdtalk moell home')
        out = cli_plug(gizmore, '$sdtalk moell yes')
        self.assertIn('money', out, 'moellring does not work.')
        out = cli_plug(gizmore, '$sdgmi giz 400xNuyen')
        out += cli_plug(gizmore, '$sdtalk moell yes')
        self.assertIn('live here', out, 'moellring does not work.')
        self.assertIn('accomplished', out, 'moellring does not work.')
        out = cli_plug(gizmore, '$sdsleep')
        self.assertIn('to bed', out, 'quest no work.')
        out = cli_plug(gizmore, '$sdgmi giz 800xNuyen')
        out += cli_plug(gizmore, '$sdtalk moell rent')
        self.assertIn('accomplished', out, 'quest no work.')

    async def test_10_quest_garage1(self):
        gizmore = await self.fresh_gizmore(False)
        out = cli_plug(gizmore, '$sdgml giz inside Gara')
        self.assertIn('Garage', out, 'gml no work.')
        out = cli_plug(gizmore, '$sdtalk bar work')
        self.assertIn('job', out, 'talk no work.')
        out = cli_plug(gizmore, '$sdtalk bar yes')
        self.assertIn('new quest', out, 'talk no work.')
        out = cli_plug(gizmore, '$sdtalk bar jawoll')
        out = cli_plug(gizmore, '$sdkp')
        self.assertIn('Jawoll', out, 'talk no work.')
        out = cli_plug(gizmore, '$sdgml giz inside Jaw')
        self.assertIn('Jawoll', out, 'gml no work.')
        out = cli_plug(gizmore, '$sdbuy beer 50')
        self.assertIn('LargeBeer', out, 'buy no work.')
        out = cli_plug(gizmore, '$sdgml giz inside Gara')
        self.assertIn('Garage', out, 'gml no work.')
        out = cli_plug(gizmore, '$sdgive bark 40xbee')
        self.assertIn('Barkeep', out, 'gml no work.')
        out = cli_plug(gizmore, '$sdgive bark 11xbee')
        self.assertIn('10', out, 'gmlss no work.')
        self.assertIn('accomplish', out, 'gml no work.')

    async def test_20_quest_bam(self):
        gizmore = await self.fresh_gizmore(False)
        out = cli_plug(gizmore, '$sdgml giz inside Gunz')
        self.assertIn('Gunzelin', out, 'gml no work.')
        out = cli_plug(gizmore, '$sdcourses')
        self.assertIn('Math', out, 'courses no work.')
        out = cli_plug(gizmore, '$sdgmi giz 1000xNuy')
        self.assertIn('1000', out, 'gmi no work.')
        out = cli_plug(gizmore, '$sdtalk Mi hello')
        self.assertIn('Besser als Miehe', out, 'talk#1 no work.')
        out = cli_plug(gizmore, '$sdlearn mat')
        self.assertIn('Math', out, 'learn no work.')
        out = cli_plug(gizmore, '$sdgmk giz 10')
        self.assertIn('You gave', out, 'learn no work.')
        out = cli_plug(gizmore, '$sdlvlup --confirm=1 mat')
        self.assertIn('Math', out, 'lvlup does not work.')
        out = cli_plug(gizmore, '$sdtalk Mi hello')
        self.assertIn('learn', out, 'talk#2 no work.')
        Random.init(31337)
        out = cli_plug(gizmore, '$sdtalk Mi learn')
        self.assertIn('powered by', out, 'talk#2 no work.')
        out = cli_plug(gizmore, '$sdtalk Mi 2t')
        self.assertIn('correct', out, 'talk#3 no work.')
        self.assertIn('accomplish', out, 'talk#3.1 no work.')
        self.assertIn('rewarded with skill', out, 'talk#3.2 no work.')

    async def test_30_quest_hate(self):
        gizmore = await self.fresh_gizmore()
        out = cli_plug(gizmore, '$sdgml giz inside Waff')
        self.assertIn('Kief', out, 'gml no work.')
        out = cli_plug(gizmore, '$sdtalk cash hello')
        self.assertIn('Hello', out, 'talk#1 no work.')
        out = cli_plug(gizmore, '$sdtalk cash work')
        self.assertIn('looking', out, 'talk#2 no work.')
        out = cli_plug(gizmore, '$sdtalk cash yes')
        self.assertIn('quest', out, 'talk#3 no work.')
        out = cli_plug(gizmore, '$sdgmi giz 8xMedki')
        self.assertIn('Medkit', out, 'talk#3 no work.')
        for i in range(Hate.NUM_KILLS):
            cli_plug(gizmore, '$sdgmt giz haider')
            await self.party_ticker_for()
            cli_plug(gizmore, '$sduse Medkit')
            await self.ticker_for()
        out = cli_plug(gizmore, '$sdtalk cash yes')
        self.assertIn('accomplished', out, 'talk#4 no work.')

    async def test_40_quest_jungle(self):
        gizmore = await self.fresh_gizmore()
        out = cli_plug(gizmore, '$sdgml giz inside alf')
        self.assertIn('Alfred', out, 'gml no work.')
        out = cli_plug(gizmore, '$sdtalk fish weed')
        out = cli_plug(gizmore, '$sdtalk fish weed')
        out = cli_plug(gizmore, '$sdtalk fish weed')
        out = cli_plug(gizmore, '$sdtalk fish weed')
        out = cli_plug(gizmore, '$sdtalk fish weed')
        out = cli_plug(gizmore, '$sdtalk fish yes')
        self.assertIn('new quest', out, '#talk no work.')
        out = cli_plug(gizmore, '$sdgml giz inside woods')
        Random.init(31337)
        i = 0
        f = 0
        for i in range(150):
            out = cli_plug(gizmore, '$sdsearch')
            if 'accomplished' in out: break
            if self.sd_gizmore().get_party().does(Action.FIGHT):
                await self.party_ticker_for()
                f += 1
        self.assertLess(i, 99, 'quest is borked #1.')
        self.assertLess(f, 20, 'quest is borked #2.')

    async def test_50_baptism(self):
        gizmore = await self.fresh_gizmore()
        out = cli_plug(gizmore, '$sdgml giz inside gar')
        self.assertIn('GarageP', out, 'gml no work.')
        out = cli_plug(gizmore, '$sdtalk matt hello')
        self.assertIn('Oh hell', out, 'talk#1 no work.')
        out = cli_plug(gizmore, '$sdtalk matt work')
        self.assertIn('civilian', out, 'talk#2 no work.')
        out = cli_plug(gizmore, '$sdtalk matt home')
        self.assertIn('looking', out, 'talk#3 no work.')
        out = cli_plug(gizmore, '$sdtalk matt home')
        self.assertIn('video', out, 'talk#4 no work.')
        out = cli_plug(gizmore, '$sdtalk matt home')
        self.assertIn('baptism', out, 'talk#5 no work.')
        out = cli_plug(gizmore, '$sdtalk matt home')
        self.assertIn('enemies', out, 'talk#6 no work.')
        out = cli_plug(gizmore, '$sdtalk matt home')
        self.assertIn('lamers', out, 'talk#7 no work.')
        out = cli_plug(gizmore, '$sdtalk matt yes')
        self.assertIn('new quest', out, 'talk#8 no work.')
        for i in range(6):
            out = cli_plug(gizmore, '$sdexp')
            await self.party_ticker_until(Action.OUTSIDE)
        out = cli_plug(gizmore, '$sdgml giz inside gar')
        self.assertIn('GarageP', out, 'gml no work.')
        out = cli_plug(gizmore, '$sdtalk matt hello')
        self.assertIn('accomplished', out, 'talk#10 no work.')

    async def test_60_bottles(self):
        gizmore = await self.fresh_gizmore()
        out = cli_plug(gizmore, '$sdgml giz in Par')
        self.assertIn('Park', out, 'gml no work.')
        out = cli_plug(gizmore, '$sdsearch')
        self.assertIn('Bottle', out, 'bottlesearch#2 no work.')
        out = cli_plug(gizmore, '$sdgml giz in market')
        self.assertIn('Marketplace', out, 'gml no work.')
        out = cli_plug(gizmore, '$sdsearch')
        self.assertIn('Bottle', out, 'bottlesearch#5 no work.')
        out = cli_plug(gizmore, '$sdgml giz in train')
        self.assertIn('TrainStat', out, 'gml no work.')
        out = cli_plug(gizmore, '$sdsearch')
        self.assertIn('Stone', out, 'bottlesearch#3 no work.')
        out = cli_plug(gizmore, '$sdtalk bum hello')
        self.assertIn('ello frie', out, 'talk#1 no work.')
        out = cli_plug(gizmore, '$sdtalk bum work')
        self.assertIn('anymore', out, 'talk#2 no work.')
        out = cli_plug(gizmore, '$sdtalk bum weed')
        self.assertIn('need weed.', out, 'talk#3 no work.')
        out = cli_plug(gizmore, '$sdtalk bum work')
        self.assertIn('easy money', out, 'talk#4 no work.')
        out = cli_plug(gizmore, '$sdtalk bum work')
        self.assertIn('collect', out, 'talk#4 no work.')
        out = cli_plug(gizmore, '$sdtalk bum yes')
        self.assertIn('new quest', out, 'talk#4 no work.')
        out = cli_plug(gizmore, '$sdexplore')
        await self.party_ticker_until('outside')
        out = cli_plug(gizmore, '$sdexplore')
        await self.party_ticker_until('outside')
        out = cli_plug(gizmore, '$sdi')
        self.assertIn('xBottle', out, 'i no work.')
        out = cli_plug(gizmore, '$sdgml giz in train')
        out = cli_plug(gizmore, '$sdgive bum 6xBottle')
        self.assertIn('accompli', out, 'quest no work.')

    async def test_70_police(self):
        giz = await self.power_gizmore(10, 'bod,bod,bod,str,qui,qui,str,str', 'Shotgun,LeatherVest,CombatHelmet,Boots,250xAmmo9mm')
        gizmore = cli_gizmore()
        out = cli_plug(gizmore, '$sdgmi giz WalkieT')
        self.assertIn('Talkie', out, 'gmi no work.')
        out = cli_plug(gizmore, '$sdu walkie')
        self.assertIn('white noise', out, 'walkie talkie no work.')
        out = cli_plug(gizmore, '$sdgml giz outside Police')
        self.assertIn('Police Station', out, 'i no work.')
        out = cli_plug(gizmore, '$sdenter')
        await self.ticker(60)
        out += all_private_messages()
        self.assertIn('no time', out, 'enter no work.')
        out = cli_plug(gizmore, '$sdu walkie')
        self.assertIn('new quest', out, 'walkie talkie #2 no work.')
        self.assertIn('Time left: ca. 1h', out, 'walkie talkie #3 no work.')
        out = cli_plug(gizmore, '$sdenter')
        await self.ticker(60)
        out += all_private_messages()
        self.assertIn('entered', out, 'enter no work #2.')
        await self.party_ticker_until(Action.INSIDE)
        Random.init(31459)
        for i in range(8):
            out = cli_plug(gizmore, '$sdexp')
            self.assertIn('explore', out, 'exp no work.')
            await self.party_ticker_until(Action.OUTSIDE)
            if giz.get_location() == self.world().World2064.PoliceStation.EvidenceRoom:
                out = cli_plug(gizmore, '$sdenter')
                break
        self.assertIn('entered', out, 'enter no work #3.')
        out = cli_plug(gizmore, '$sdsearch')
        self.assertIn('accomplished', out, 'search no work.')

    async def test_75_buds(self):
        giz = await self.power_gizmore(2, 'str,qui', 'CombatVest')
        gizmore = cli_gizmore()
        out = cli_plug(gizmore, '$sdsleep')
        await self.party_ticker_until(Action.INSIDE)
        out = cli_plug(gizmore, '$sdgmi giz weed')
        out = cli_plug(gizmore, '$sdgive mom weed')
        self.assertIn('accomplished', out, 'search no work.')
        self.assertIn('encounter', out, 'search no work.')
        await self.party_ticker_until(Action.INSIDE)



if __name__ == '__main__':
    unittest.main()
