y2064_alfred_hello = ""

########
# Fish #
########
sdqt_jungle = "Jungle"
sdqd_jungle = "Find a hidden weed farm in the Telchte Woods."
sdqs_jungle_hello = "dude... you got some weed?"
sdqs_jungle_weed1 = "I am waiting for two people for a smoke."
sdqs_jungle_weed2 = "Since days... it's wicked at the moment."
sdqs_jungle_weed3 = "I have no idea either."
sdqs_jungle_weed4 = "Well... could as well look for a hidden farm ^^"
sdqs_jungle_weed5 = "So... you are in? :D"
sdqs_jungle_yes = "yes yes"
sdqs_jungle_accept = "Go put on some serious footgear and meet me at Telchte's swampy forest."
sdqs_jungle_no = "yeah, no"
sdqs_jungle_deny = "You are a disappointment."
sdqs_jungle_home_1 = "You look for a home with Lazer?"
sdqs_jungle_home_2 = "Yeah... your mom is right."
sdqs_jungle_work_1 = "First McDonalds, now civil service?"
sdqs_jungle_work_2 = "What are you gonna do for civil service?"
sdqs_jungle_else = "What a pity."
sdqs_found_farm = "You found a hidden hemp farm."
sdqs_jungle_keep_on_1 = "Keep om **$t$search**ing. We will surely find some stash."
sdqs_jungle_keep_on_2 = "You can also $t$hire me, so we can search together."
sdqs_jungle_keep_on_3 = "Are you ready? Let us keep searching."
