##############
### Quests ###
##############
sdq0001_title = "Peninsula"
sdq0001_descr = "Find out where the weird pen is from."

sdq0002_title = "Connection"
sdq0002_descr = "Try to contact lazer to find out what might have happened."

