no_what = "No what?!"
yes_what = "Yes what?!"
sd_npc_says = '%s says: "%s"'

# Default NPC
msg_sd_talk_default_1 = "Hello"
msg_sd_talk_default_2 = "You got lighter?"
msg_sd_talk_default_3 = "You got cigarette?"
msg_sd_talk_default_4 = "Asshole!"

# 2064 home lazer
sd_lazer_home_intro1 = "Morning... we should eat something."
sd_lazer_home_intro2 = "The punks yesterday were funny, right? I bet we see some of them today again, walking below the window... should be buy snacks?"
sd_lazer_home_intro3 = "Should we walk to Mr.Marokko again? That shit is tough!"

