from typing import TYPE_CHECKING

from gdo.date.Time import Time

if TYPE_CHECKING:
    from gdo.shadowdogs.SD_Party import SD_Party
    from gdo.shadowdogs.SD_Player import SD_Player
    from gdo.shadowdogs.SD_NPC import SD_NPC


class Shadowdogs:

    
    LOCATION_NPCS: dict[str,'SD_NPC'] = {}
    PARTIES: dict[str,'SD_Party'] = {}
    PLAYERS: dict[str,'SD_Player'] = {}
    USERMAP: dict[str,'SD_Player'] = {}
    CURRENT_PLAYER: 'SD_Player' = None

    ITEM_COUNT_SEPERATOR = 'x'
    MODIFIER_SEPERATOR = '_of_'
    ITEM_SEPERATOR = ','

    RARE_NO = 35
    RARE_LOW = 21
    RARE_MEDIUM = 12
    RARE_HIGH = 5
    RARE_HIGHER = 3
    RARE_ULTRA = 1

    NUYEN = '¥'
    NUYEN_PER_CREDIT = 250

    RUNNING_LEVEL: int = 5

    XP_PER_KARMA = 9
    XP_PER_KARMA_PER_LEVEL = 1
    XP_PER_KARMA_POW = 1.41

    KARMA_PER_SKILL = 3
    KARMA_PER_ATTRIBUTE = 3
    MAX_ATTRIBUTE_LEVEL = 12
    MAX_ATTRIBUTE_PER_BONUS = 2
    MAX_SKILL_LEVEL = 24

    XP_PER_LEVEL_BASE = 8
    XP_PER_LEVEL_POW = {
        'elve': 2.75,
        'halfelve': 2.53,
        'human': 2.44,
        'dwarf': 2.40,
        'halforc': 2.35,
        'orc': 2.30,
        'troll': 2.25,
    }


    SECONDS_PER_TICK = 1
    SECONDS_PER_HP_SLEEP = 30
    SECONDS_PER_FOODING = 300
    FOOD_PER_TICK = 1
    WATER_PER_TICK = 1

    SECONDS_INITIATIVE = 60
    SECONDS_INITIATIVE_BONUS_PER_QUICKNESS = 1
    SECONDS_PER_METER = 10

    SECONDS_PEINE_OBERG = Time.ONE_MINUTE * 35
    SECONDS_PEINE_NAUEN = Time.ONE_HOUR * 2.5

    METERS_PER_FORWARD = 2
    GIVE_SECONDS_PER_WEIGHT = 0.003

    MAX_WEIGHT_BASE = 2600
    MAX_WEIGHT_PER_STRENGTH = 1200
    MAX_WEIGHT_PER_BODY = 350
    MAX_WEIGHT_FACTOR = 1.8

    HP_PER_BODY = 2
    HP_PER_BODY_SLEEP = 1
    HP_PER_STRENGTH = 1
    HP_PER_LEVEL = 0.5

    MP_PER_MAGIC = 2
    MP_PER_MAGIC_SLEEP = 1
    MP_PER_INTELLIGENCE = 2
    MP_PER_WISDOM = 1
    MP_PER_LEVEL = 0.25

    ATK_PER_DEX = 2
    ATK_PER_QUI = 0.5

    DEF_PER_DEX = 0.5
    DEF_PER_QUI = 0.5

    MAX_DISTANCE = 24

    GOTO_SECONDS_POW = 2.4
    GOTO_DIVISOR_PER_PLACE = 1

    NPC_ENCOUNTER_CHANCE = 100
    NPC_ENCOUNTER_NONE_CHANCE = 16000
    MIN_ENCOUNTERS = 1
    MAX_ENCOUNTER_BASE = 2
    LEVELS_PER_MAX_ENCOUNTER = 8

    MEET_CHANCE_MEET = 25
    MEET_CHANCE_TOTAL = 100000
    MEET_CHANCE_DIV_PER_SQKM = 1.0

    EXPLORE_ETA_MIN = 180
    EXPLORE_ETA_PER_SQKM = 45
    EXPLORE_ETA_BONUS_PER_QUICKNESS = 10
    EXPLORE_ETA_BONUS_PER_SPEED = 60
    EXPLORE_NONE_CHANCE_PER_SQKM = 15

    LOOT_CHANCE_NOTHING = 455
    LOOT_CHANCE_EQUIPMENT = 8
    LOOT_CHANCE_EQUIPMENT_PER_LUCK = 0.5
    LOOT_CHANCE_INVENTORY = 10
    LOOT_CHANCE_INVENTORY_PER_LUCK = 0.5
    LOOT_CHANCE_RANDOM = 4
    LOOT_CHANCE_RANDOM_PER_LUCK = 1
    LOOT_CHANCE_RANDOM_MODIFIER = 2
    LOOT_CHANCE_RANDOM_MODIFIER_PER_LUCK = 0.5
    LOOT_CHANCE_NUYEN = 33
    LOOT_CHANCE_NUYEN_PER_LUCK = 0.5
    LOOT_NUYEN_MIN = 5
    LOOT_NUYEN_BASE = 40
    LOOT_NUYEN_EXP_LEVEL = 1.41
    LOOT_NUYEN_PER_LUCK = 2

    SHOUT_MIN_LEVEL = 10
    SHOUT_TIMEOUT = 500
    SHOUT_TIMEOUT_PER_LEVEL = 10

    STORE_PRICE_REDUCTION_PER_TRADE = 0.002
    STORE_PRICE_REDUCTION_PER_CHARISMA = 0.001

    RELOAD_MIN_TIME = 10
    RELOAD_SECONDS_PER_QUICKNESS = 1

    CRIT_CHANCE_PERCENT = 10
    CRIT_CHANCE_PER_AIM = 1

    THROW_TTME_PER_QUICKNESS = 1
    THROW_TIME_BASE = 30

    CAST_FAIL_MULTIPLE_PER_LEVEL = 2.5
    CAST_MIN_CAST_TIME = 15

    @classmethod
    def display_nuyen(cls, nuyen: int) -> str:
        return str(nuyen) + cls.NUYEN
