y2064_peine_seniorhome = "SeniorHome"
y2064_peine_seniorhome_inside = "You see the reception and a **Nurse**."
y2064_peine_seniorhome_outside = "You find a home for the elderly people. It looks like an old military building."

