y2064_peine_waffenkief = "WaffenKief"
y2064_peine_waffenkief_inside = "You see the reception and a **Salesman**."
y2064_peine_waffenkief_outside = "Inside the city you find a weapon store. Probably not the hottest stuff, but worth a look."
