# 2064 home lazer
sd_lazer_home_intro1 = "Morning... we should eat something."
sd_lazer_home_intro2 = "The punks yesterday were funny, right? I bet we see some of them today again, walking below the window... should we buy snacks?"
sd_lazer_home_intro3 = "Should we walk to Mr.Marokko again? That weed is tough!"
sd_lazer_home_weed = "Yeah man, we can find a **home** afterwards."

# Home mom
sdqs_mom_no_weed = "You know i get sick when i smoke. I never tried it!"

# home dejavu
sdqs_dejavu_hello = "Hello big brother, can i come watching you guys playing the Amiga1200?"
sdqs_dejavu_home = "I like it here."
sdqs_dejavu_work = "HeHe. Soon i am turning 12 years old :)"
sdqs_dejavu_weed = "Weed. I am not stupid."

# home thomas
sdqs_thomas_hello = ""
sdqs_thomas_work = ""
sdqs_thomas_weed = ""
sdqs_thomas_home = ""

# car repair Peter
sdqs_peterg_hello = "Hello, what's up?"
sdqs_peterg_weed = "I rarely smoke this shit."
sdqs_peterg_home = "I heard my son Theo want's to move in with you as well."
sdqs_peterg_quest = "I am out of tires. Can you pick some from the scrapyard? I need 8 pieces."
sdqs_peterg_quest2 = "So?"
sdqs_peterg_yes = "Yes what?"
sdqs_peterg_yes2 = "Great! See you soon!"
sdqs_peterg_no = "Ok."

# Arnecke
sdqs_arnecke_hello = ""
sdqs_arnecke_weed = ""
sdqs_arnecke_home = ""
sdqs_arnecke_quest = ""
sdqs_arnecke_quest2 = ""
sdqs_arnecke_yes = ""
sdqs_arnecke_yes2 = ""
self.qv_set = ""
sdqs_arnecke_no = ""
