# 2064 home lazer
sd_lazer_home_intro1 = "Morning... we should eat something."
sd_lazer_home_intro2 = "The punks yesterday were funny, right? I bet we see some of them today again, walking below the window... should we buy snacks?"
sd_lazer_home_intro3 = "Should we walk to Mr.Marokko again? That weed is tough!"
sd_lazer_home_weed = "Yeah man, we can find a **home** afterwards."

# Home mom
sdqs_mom_no_weed = "You know i get sick when i smoke. I never tried it!"

# home dejavu
sdqs_dejavu_hello = "Hello big brother, can i come watching you guys playing the Amiga1200?"
sdqs_dejavu_home = "I like it here."
sdqs_dejavu_work = "HeHe. Soon i am turning 12 years old :)"
sdqs_dejavu_weed = "Weed. I am not stupid."

# home thomas
sdqs_thomas_hello = ""
sdqs_thomas_work = ""
sdqs_thomas_weed = ""
sdqs_thomas_home = ""

# car repair Peter
sdqs_peterg_hello = "Hello, what's up?"
sdqs_peterg_weed = "I rarely smoke this shit."
sdqs_peterg_home = "I heard my son Theo want's to move in with you as well."
sdqs_peterg_quest = "I am out of tires. Can you pick some from the scrapyard? I need 8 pieces."
sdqs_peterg_quest2 = "So?"
sdqs_peterg_yes = "Yes what?"
sdqs_peterg_yes2 = "Great! See you soon!"
sdqs_peterg_no = "Ok."

# Arnecke
sdqs_arnecke_hello = "Hi there buddy"
sdqs_arnecke_weed = "I am waiting for a friend. I'll call you."
sdqs_arnecke_home = "Ouh Man, that was it back in Ilside."
sdqs_arnecke_quest = "You can help crush those haiders. OK?"
sdqs_arnecke_quest2 = "What do you think?"
sdqs_arnecke_yes = "Yes?"
sdqs_arnecke_yes2 = "That's the spirit."
sdqs_arnecke_no = "Ok."

# Plants
sdqs_plants_hello = "Greetings, you are looking for a job?"
sdqs_plants_weed = "We don't sell those plants here."
sdqs_plants_home = "I am from Stederdorf."
sdqs_plants_quest = "Oh you wan't to have a minijob?"
sdqs_plants_quest2 = "You can help with the plants. What do you say?"
sdqs_plants_yes = "Yes?"
sdqs_plants_yes2 = "Ok. Great. you can #work here."
sdqs_plants_no = "Yes, No."

# Trolley
sdqs_felix_hello = "Hi there! How is it?"
sdqs_felix_weed = "Uh No... Never did that."
sdqs_felix_home = "I lost most of my family according to my day-off excuses."
sdqs_felix_quest = "You can do the trolleys in the parking lot, ok?"
sdqs_felix_quest2 = "You ready?"
sdqs_felix_yes = "Yes."
sdqs_felix_yes2 = "Ok, then."
sdqs_felix_no = "No"
