#############
# Carpenter #
#############
sdqt_carpenter = "Carpenter"
sdqd_carpenter = "Help the Winkelmanns to recreate their roof to get a nice reward."

#############
# Irmingard #
#############
sd_irmingard_hello = "Hey Christian, back in Bothel again?"

#########
# Fritz #
#########
sdqs_Fritz_W_hello = ""
sdqs_Fritz_W_work = ""
sdqs_Fritz_W_weed = ""
sdqs_Fritz_W_home = ""
sdqs_Fritz_W_ninja = ""
sdqs_Fritz_W_other = ""

