from gdo.shadowdogs.engine.Shadowdogs import Shadowdogs as SD

class shadowhelp():

    HELP = {
        'en': {
            "help": {
                "0": "I know these topics:",
                "general": {
                    "bold": "Bold words have an own help page, but the context might be a bit off, as those links are automatically generated by simple word matching.",
                    "setup": "Shadowdogs plays on earth in the year 2064-2088. ",
                },
                "levels": {
                    "0": "Level related;",
                    "player_level": "In your status you will see your base and effective level like this: L1(5). This means you have base level 1, and an effective level of 5. The base level is used in requirements, like travelling to other areas, and the effective level is used in combat "
                                    "restrictions.",
                    "npc_level": "The NPC levels affect what items you can loot.",
                },
                "attributes": {
                    "0": "Known attributes:",
                    "body": f"Increases your max_hp by {SD.HP_PER_BODY}.",
                    "magic": f"Increases your max_mp by {SD.MP_PER_MAGIC}.",
                },
                "skills": {
                    "0": "Known skills:",
                    "trading": "Lowers your buy prices and raises your sell prices.",
                },
                "stats": {
                    "0": "Known stats:",
                    "mp": "Your magic points to cast spell.",
                    "max_mp": "Your maximum amount of mp.",
                },
                "combat": {
                    "0": "Topics:",
                    "stack": "In combat you have a one item stack. Your last command gets executed which defaults to $t$attack <random> to lock a random target.",
                    "death": "When you die you will loose one equipment item. You will respawn at the closest respawn location.",
                    "loot": "",
                },
                "commands": {
                    "0": "Known commands:",
                    "action_cmds": {
                        "0": "Leader only action commands:",
                        "enter": "If you are outside a location, you can usually $t$enter it.",
                    },
                    "chat_cmds": {

                    },
                    "combat_cmds": {

                    },
                    "hack_cmds": {

                    },
                    "info_cmds": {

                    },
                    "location_cmds": {

                    },
                    "level_cmds": {

                    },
                    "settings_cmds": {

                    },
                    "usable_cmds": {

                    },
                },
                "world": {
                    "0": "SD-World:",
                },
                "places": {
                    "0": "Topics:",
                },
            }
        },
    }

