module_shadowdogs = "Shadowdogs"

############
# Factions #
############
gdo_faction = "Faction"
sd_freeborn = "Freeborn"
sd_concordium = "Concordium"
sd_seekers = "Seekers"
sd_iron = "Iron"
sd__freeborn = "The Freeborn seek absolute Freedom, but without order, will they survive?"
sd__concordium = "The Concordium crave Peace, but will their control become a prison?"
sd__seekers = "The Seekers hunt for Truth, but can truth exist without chaos?"
sd__iron = "The Iron Pact embrace War, but will their strength destroy them in the end?"

########
# GDTs #
########
err_sd_unknown_mods_mapping = "Unknown modifier magic word: %s."

#########
# Items #
#########
sd_receive_item_gmi = "You received %s from the GM %s."
sd_receive_item_loot = "You received %s from looting the %s."

################
### Commands ###
################

############
# MethodSD #
############
err_sd_player_required = "You need to $trigger$sdstart first."
err_sd_not_here = "This does not work here."
err_sd_not_now = "You cannot do this now."

##########
# Enable #
##########
mt_shadowdogs_enable = "Enable"
md_shadowdogs_enable = "Enable Shadowdogs inside a channel"
msg_sd_enabled = "Shadowdogs has been enabled."
err_sd_stub = "Shadowdogs unimplemented error"

#########
# Start #
#########
mt_shadowdogs_start = "Start Shadowdogs"
md_shadowdogs_start = "Create a character in Shadowdogs."
msg_sd_started = "You created your character, a %s %s."
err_sd_already_started = "You created a character already. You can $sdreset to start over."
msg_sd_new_player = "A new player joined the underground shadowdogs; %s the %s %s!"
sd_story_1 = "You wake up. Feeling dizy and still alcoholized."
sd_story_2 = "Your attempts to uncover the secrets of this world seem pointless. You somehow feel outta place..."

#########
# Equip #
#########
mt_shadowdogs_equip = "Equip Item"
md_shadowdogs_equip = "Equip yourself with an Item."
msg_sd_item_equip = "You use %s as your %s from now on. %s busy."

#############
# Inventory #
#############
mt_shadowdogs_inventory = "Inventory"
md_shadowdogs_inventory = "Show your inventory. Page is the first parameter. Use --search=foo to search."

#########
# Reset #
#########
mt_shadowdogs_reset = "Reset Character"
md_shadowdogs_reset = "Reset your Shadowdogs Character."
msg_sd_reset_confirm = "Please use $sdreset --confirm=1 to confirm."
err_sd_start_first = "You have to use $sdstart first."
msg_sd_reset = "Your account has been deleted so you can start over."

#########
# Fight #
#########
mt_shadowdogs_fight = "Fight"
md_shadowdogs_fight = "Fight an opposing party."
msg_sd_fight_started = "You encounter %s."

##########
### GM ###
##########

#######
# GMI #
#######
mt_shadowdogs_gmi = "GM Item"
md_shadowdogs_gmi = "GM Command - Create an item for a player."
msg_sd_gmi_success = "You successfully gave %s for %s."
