from gdo.shadowdogs.engine.Shadowdogs import Shadowdogs as SD

class shadowhelp():

    HELP = {
        'en': {
            "help": {
                "0": "I know these topics:",
                "general": {
                    "bold": "Bold words have an own help page, but the context might be a bit off, as those links are automatically generated by simple word matching.",
                    "setup": "Shadowdogs plays on earth in the year 2064-2088. ",
                },
                "places": {
                    "0": "Topics:",
                },
                "skills": {
                    "0": "Known skills:",
                    "body": f"Increases your max_hp by {SD.HP_PER_BODY}.",
                    "magic": f"Increases your max_mp by {SD.MP_PER_MAGIC}.",
                },
                "stats": {
                    "0": "Known stats:",
                    "mp": "Your magic points to cast spell.",
                    "max_mp": "Your maximum amount of mp.",
                },
                "combat": {
                    "0": "Topics:",
                    "stack": "In combat you have a one item stack. Your last command gets executed which defaults to $t$attack <random> to lock a random target.",
                    "death": "When you die you will loose one equipment item. You will respawn at the closest respawn location.",
                },
            }
        },
    }

