########
# Dust #
#########

#############
# Edeltraut #
#############



#########
# Frank #
#########
sdqs_frank_dux_hello = "Hello"
sdqs_frank_dux_weed = "You shut the f*** up. I gonna getcha."
sdqs_frank_dux_work = "Yes, i will become a police officer."
sdqs_frank_dux_home = "Yeah it's nice here. Btw, do you guys still have my **ninja** fighting techniques book?"
sdqs_frank_dux_ninja = "You won't believe what happened in the disco last night."
sdqs_frank_dux_lost = "Get lost you scumbags"

